modifications

diff --git a/06-loops2-sh b/06-loops2-sh
--- a/06-loops2-sh
+++ b/06-loops2-sh
@@ -5,15 +5,36 @@ SCRIPT_NAME=$0
 LOGFILE=$LOGSDIR/$0/$DATE.log
 USERID=$(id -u)
 R="\e[31m"
+R="\e[32m"
 N="\e[0m"
+R="\e[33m"
+
 
 if [ $USERID -ne 0 ]
 then
      echo -e "$R ERROR:pls run this script with root user $N"
      exit 1
 fi
-
+validate(){
+    if [ $1 -ne 0 ];
+    then 
+    echo -e "$R installing $2 .. FAILURE $N"
+    exit 1
+    else
+    echo -e "Installing $2 ... $G SUCESS $N"
+    fi
+}
 for i in $@
 do
+yum list installed $i &>>$LOGFILE
+if[ $? -ne 0 ]
+then
+     echo "$i is not installed, let's install it"
+     yum install $i -y &>>$LOGFILE
+     validate $? "$i"
+
+else
+     echo -e "$Y $i is already installed $N"
+fi
 yum install $i -y
 done
